defaults:
  - base.yaml
  - _self_

encoder_name: "openclip"
pretrained: True
predefined_preprocessing: True
freeze_encoder: True
checkpoint_name: "hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224"